### ISSUE TITLE
VBOX_E_OBJECT_NOT_FOUND - Could not find a registered machine named 'Mojave'

### ISSUE THREAD

**Issue by pstoller78** [img2tab/okiomov#9]
I'm getting the following error when running the sh script.  What actions do I need to take to correct?

VBoxManage.exe: error: Could not find a registered machine named 'Mojave'
VBoxManage.exe: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee IUnknown
VBoxManage.exe: error: Context: "FindMachine(Bstr(pszVM).raw(), machine.asOutParam())" at line 595 of file VBoxManageMisc.cpp

**Comment by sej7278** [comment]
i got that when the shell script fell over half way through, the workaround is to use a different ```vmname``` like "Mojave2", i guess it leaves some crud somewhere in the vbox config

**Comment by img2tab** [comment]
Fixed.

**Comment by kschneier** [comment]
I am still getting this error with the current version; I'm using Cygwin and I can't get anywhere because it just tells me I don't have a registered machine with my `vmname`.  What was fixed when this was closed on January 3rd?
